# Generated by Django 2.1.7 on 2019-04-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('capacity', models.IntegerField()),
                ('year_opened', models.IntegerField()),
                ('year_closed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arena',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('abbreviation', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'conference',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('abbreviation', models.CharField(max_length=8)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Conference')),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('tipoff', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='GamePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Game')),
            ],
            options={
                'db_table': 'game_period',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('year_founded', models.IntegerField()),
            ],
            options={
                'db_table': 'league',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.CharField(max_length=16)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(max_length=64)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('preferred_name', models.CharField(blank=True, max_length=32, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('college', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'player_position',
            },
        ),
        migrations.CreateModel(
            name='PlayerTeamSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'player_team_season',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('abbreviation', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season_start', models.DateField(blank=True, null=True)),
                ('playoff_start', models.DateField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.League')),
            ],
            options={
                'db_table': 'season',
            },
        ),
        migrations.CreateModel(
            name='Statline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp', models.IntegerField(blank=True, null=True)),
                ('fg', models.IntegerField()),
                ('fga', models.IntegerField(blank=True, null=True)),
                ('fg_pct', models.FloatField(blank=True, null=True)),
                ('tp', models.IntegerField(blank=True, null=True)),
                ('tpa', models.IntegerField(blank=True, null=True)),
                ('tp_pct', models.FloatField(blank=True, null=True)),
                ('ft', models.IntegerField(blank=True, null=True)),
                ('fta', models.IntegerField(blank=True, null=True)),
                ('ft_pct', models.FloatField(blank=True, null=True)),
                ('orb', models.IntegerField(blank=True, null=True)),
                ('drb', models.IntegerField(blank=True, null=True)),
                ('trb', models.IntegerField(blank=True, null=True)),
                ('ast', models.IntegerField(blank=True, null=True)),
                ('stl', models.IntegerField(blank=True, null=True)),
                ('blk', models.IntegerField(blank=True, null=True)),
                ('tov', models.IntegerField(blank=True, null=True)),
                ('pf', models.IntegerField(blank=True, null=True)),
                ('pts', models.IntegerField()),
            ],
            options={
                'db_table': 'statline',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=16)),
                ('year_founded', models.IntegerField()),
                ('abbreviation', models.CharField(max_length=8)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Arena')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Division')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Team')),
            ],
            options={
                'db_table': 'team_season',
            },
        ),
        migrations.CreateModel(
            name='AdvancedStatline',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stats.Statline')),
                ('ts', models.FloatField(blank=True, null=True)),
                ('efg', models.FloatField(blank=True, null=True)),
                ('tpar', models.FloatField(blank=True, null=True)),
                ('ftr', models.FloatField(blank=True, null=True)),
                ('orb_pct', models.FloatField()),
                ('drb_pct', models.FloatField()),
                ('trb_pct', models.FloatField()),
                ('ast_pct', models.FloatField()),
                ('stl_pct', models.FloatField()),
                ('blk_pct', models.FloatField()),
                ('tov_pct', models.FloatField(blank=True, null=True)),
                ('usg_rate', models.FloatField()),
                ('ortg', models.IntegerField()),
                ('drtg', models.IntegerField()),
            ],
            options={
                'db_table': 'advanced_statline',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stats.Person')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('shooting_hand', models.CharField(max_length=5)),
                ('image_url', models.CharField(max_length=128, null=True)),
                ('final_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_season', to='stats.Season')),
                ('rookie_season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rookie_season', to='stats.Season')),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='PlayerStatline',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stats.Statline')),
                ('started', models.BooleanField(blank=True, null=True)),
                ('plus_minus', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Player')),
            ],
            options={
                'db_table': 'player_statline',
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stats.Person')),
                ('jersey_number', models.IntegerField()),
                ('final_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ref_final_season', to='stats.Season')),
                ('rookie_season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ref_rookie_season', to='stats.Season')),
            ],
            options={
                'db_table': 'referee',
            },
        ),
        migrations.CreateModel(
            name='TeamEmployee',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stats.Person')),
                ('role', models.CharField(max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Team')),
            ],
            options={
                'db_table': 'team_employee',
            },
        ),
        migrations.AddField(
            model_name='statline',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Game'),
        ),
        migrations.AddField(
            model_name='statline',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Team'),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='team_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.TeamSeason'),
        ),
        migrations.AddField(
            model_name='playerposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Position'),
        ),
        migrations.AddField(
            model_name='person',
            name='birthplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Location'),
        ),
        migrations.AddField(
            model_name='game',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team', to='stats.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team', to='stats.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner', to='stats.Team'),
        ),
        migrations.AddField(
            model_name='conference',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.League'),
        ),
        migrations.AddField(
            model_name='arena',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Location'),
        ),
        migrations.AddField(
            model_name='playerteamseason',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Player'),
        ),
        migrations.AddField(
            model_name='playerposition',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='ref_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_ref', to='stats.Referee'),
        ),
        migrations.AddField(
            model_name='game',
            name='ref_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='third_ref', to='stats.Referee'),
        ),
        migrations.AddField(
            model_name='game',
            name='ref_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_ref', to='stats.Referee'),
        ),
    ]
