# Generated by Django 2.1.7 on 2019-03-31 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('capacity', models.IntegerField()),
                ('year_opened', models.IntegerField()),
                ('year_closed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arena',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('abbreviation', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'conference',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('abbreviation', models.CharField(max_length=8)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Conference')),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('year_founded', models.IntegerField()),
            ],
            options={
                'db_table': 'league',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.CharField(max_length=16)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(max_length=64)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=16)),
                ('middle_name', models.CharField(blank=True, max_length=16, null=True)),
                ('preferred_name', models.CharField(blank=True, max_length=16, null=True)),
                ('dob', models.DateField()),
                ('college', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'player_position',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('abbreviation', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season_start', models.DateField(blank=True, null=True)),
                ('playoff_start', models.DateField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.League')),
            ],
            options={
                'db_table': 'season',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=16)),
                ('year_founded', models.IntegerField()),
                ('abbreviation', models.CharField(max_length=8)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Arena')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Division')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stats.Person')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('shooting_hand', models.CharField(max_length=5)),
                ('image_url', models.CharField(max_length=128)),
                ('final_season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_season', to='stats.Season')),
                ('rookie_season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rookie_season', to='stats.Season')),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stats.Person')),
                ('jersey_number', models.IntegerField()),
                ('rookie_season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Season')),
            ],
            options={
                'db_table': 'referee',
            },
        ),
        migrations.CreateModel(
            name='TeamEmployee',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='stats.Person')),
                ('role', models.CharField(max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Team')),
            ],
            options={
                'db_table': 'team_employee',
            },
        ),
        migrations.AddField(
            model_name='playerposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Position'),
        ),
        migrations.AddField(
            model_name='person',
            name='birthplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Location'),
        ),
        migrations.AddField(
            model_name='conference',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.League'),
        ),
        migrations.AddField(
            model_name='arena',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Location'),
        ),
        migrations.AddField(
            model_name='playerposition',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Player'),
        ),
    ]
