# Generated by Django 2.1.7 on 2019-03-14 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('capacity', models.IntegerField()),
                ('year_opened', models.IntegerField()),
                ('year_closed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arena',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('abbreviation', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'conference',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('abbreviation', models.CharField(max_length=8)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Conference')),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('year_founded', models.IntegerField()),
            ],
            options={
                'db_table': 'league',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(max_length=64)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('type', models.CharField(max_length=32)),
                ('debut_year', models.IntegerField(blank=True, null=True)),
                ('final_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logo',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=16)),
                ('year_founded', models.IntegerField()),
                ('abbreviation', models.CharField(max_length=8)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Arena')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Division')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.AddField(
            model_name='logo',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Team'),
        ),
        migrations.AddField(
            model_name='conference',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.League'),
        ),
        migrations.AddField(
            model_name='arena',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stats.Location'),
        ),
    ]
