# Generated by Django 2.1.7 on 2019-05-09 02:50

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        TrigramExtension()
    ]
