# Generated by Django 2.1.7 on 2019-03-31 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20190331_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='final_season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_season', to='stats.Season'),
        ),
        migrations.AlterField(
            model_name='player',
            name='image_url',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
