# Generated by Django 2.1.7 on 2019-04-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20190331_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='college',
            field=models.TextField(blank=True, null=True),
        ),
    ]
