
export const yearToSeason = (year) => {
    const startYear = year - 1;
    let endYear = year - 2000;
    if (endYear < 0)
                endYear += 100; 
    return `${startYear}-${endYear.toString().padStart(2,'0')}`;
};

export const statNameMap = {
    "mp": "MP",
    "fg": "FG",
    "fga": "FGA",
    "fgPct": "FG%",
    "tp": "3P",
    "tpa": "3PA",
    "tpPct": "3P%",
    "ft": "FT",
    "fta": "FTA",
    "ftPct": "FT%",
    "orb": "ORB",
    "drb": "DRB",
    "trb": "TRB",
    "ast": "AST",
    "stl": "STL",
    "blk": "BLK",
    "tov": "TOV",
    "pf": "Fouls",
    "pts": "Points",
    "plusMinus": "+/-",
    "starts": "GS",
    "started": "GS",
    "ts": "TS%",
    "efg": "eFG%",
    "tpar": "3PA Rate", 
    "ftr": "FT Rate", 
    "orbPct": "OReb%", 
    "drbPct": "DReb%",
    "trbPct": "Rebound %", 
    "astPct": "Assist %", 
    "stlPct": "Steal %", 
    "blkPct": "Block %", 
    "tovPct": "TOV%", 
    "usgRate": "Usage Rate", 
    "ortg": "ORTG", 
    "drtg": "DRTG",

    "": "",
    "GS": "Games Started",
    "TRB": "Total Rebounds",
    "AST": "Assists",
    "STL": "Steals",
    "BLK": "Blocks",
    "TOV": "Turnover",
    "TOV%": "Turnover %",
    "TS%": "True Shooting %",
    "ORTG": "Offensive Rating",
    "DRTG": "Defensive Rating",
    "FG": "Field Goals Made",
    "FGA": "Field Goals Attempted",
    "FG%": "Field Goal %",
    "Min": "Minutes Played",
    "3P": "3 Pointers Made",
    "3PA": "3 Pointers Attempted",
    "3P%": "3 Point Field Goal %",
    "FT": "Free Throws Made",
    "FTA": "Free Throws Attempted",
    "FT%": "Free Throw %",
    "": "",
};